skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
perp_dex = "CSukCdZ8m3Mzrvsj5tSL2XPAdPuqG4H7ExQkFhSF6AsA"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
